### ISSUE TITLE
VladMaska

### ISSUE THREAD

**Issue by TheVladMaska** [0x636f6465/code#1]
### Tell more about you:
* First/Last name: Vlad Maska
* Portfolio: js, css, html
 * Somelink
 * Somelink
* Links for social media:
 * IG:
 * Twitter: https://twitter.com/maska_vlad
 * Github: https://github.com/TheVladMaska
 * Else:
  * 
  *
  *

**Comment by misha-marinenko-official** [comment]
Добро пожаловать!
